package com.aiburpcopilot.utils;

import java.nio.charset.StandardCharsets;

/**
 * Marks requests generated by the verification engine so they are not fed
 * back into the analysis/history pipeline when Burp observes them.
 */
public final class InternalTrafficMarker {

    public static final String HEADER_NAME = "X-AI-Burp-Copilot-Internal";
    public static final String HEADER_VALUE = "verification";

    private InternalTrafficMarker() {}

    public static boolean isMarkerHeader(String name) {
        return HEADER_NAME.equalsIgnoreCase(name);
    }

    public static boolean isMarked(String name, String value) {
        return isMarkerHeader(name) && HEADER_VALUE.equalsIgnoreCase(value != null ? value.trim() : "");
    }

    public static byte[] ensureMarked(byte[] rawRequest) {
        if (rawRequest == null || rawRequest.length == 0) {
            return rawRequest;
        }
        String raw = new String(rawRequest, StandardCharsets.UTF_8);
        if (raw.toLowerCase().contains(HEADER_NAME.toLowerCase() + ":")) {
            return rawRequest;
        }

        int lineEnd = raw.indexOf("\r\n");
        String newline = "\r\n";
        if (lineEnd < 0) {
            lineEnd = raw.indexOf('\n');
            newline = "\n";
        }
        if (lineEnd < 0) {
            return rawRequest;
        }

        String marked = raw.substring(0, lineEnd + newline.length())
                + HEADER_NAME + ": " + HEADER_VALUE + newline
                + raw.substring(lineEnd + newline.length());
        return marked.getBytes(StandardCharsets.UTF_8);
    }
}
